export enum InvestmentStatus {
  WAITING_FOR_SUBSCRIPTION_AGREEMENT = 'WAITING_FOR_SUBSCRIPTION_AGREEMENT',
  WAITING_FOR_FEES_APPROVAL = 'WAITING_FOR_FEES_APPROVAL',
  WAITING_FOR_INVESTMENT_START = 'WAITING_FOR_INVESTMENT_START',
  IN_PROGRESS = 'IN_PROGRESS',
  FUNDED = 'FUNDED',
  FAILED = 'FAILED',
  FINISHED = 'FINISHED',
}

export enum ScheduledBy {
  DIRECT = 'DIRECT',
  SCHEDULER = 'SCHEDULER',
}
