export enum Statuses {
  WAITING_FOR_SUBSCRIPTION_AGREEMENT = 'WAITING_FOR_SUBSCRIPTION_AGREEMENT',
  WAITING_FOR_FEES_APPROVAL = 'WAITING_FOR_FEES_APPROVAL',
  WAITING_FOR_INVESTMENT_START = 'WAITING_FOR_INVESTMENT_START',
  IN_PROGRESS = 'IN_PROGRESS',
  FUNDED = 'FUNDED',
  FAILED = 'FAILED',
  FINISHED = 'FINISHED',
}

export enum ScheduledBy {
  DIRECT = 'DIRECT',
  SCHEDULER = 'SCHEDULER',
}

export enum AgreementTypes {
  DIRECT_DEPOSIT = 'DIRECT_DEPOSIT',
  RECURRING_INVESTMENT = 'RECURRING_INVESTMENT',
}

export enum SubscriptionAgreementStatus {
  WAITING_FOR_SIGNATURE = 'WAITING_FOR_SIGNATURE',
  SIGNED = 'SIGNED',
}
