export enum TransactionState {
    Same,
    Initialized,
    TradeAwaiting,
    SigningSubscriptionAwaiting,
    FundsTransferAwaiting,
    PaymentAwaiting,
    SharesIssuanceAwaiting,
    TradeUnwindAwaiting,
    ManualActionAwaiting,
    AdminManualActionAwaiting,
    CompletedWithFailure,
    CompletedWithSuccess,
    VerificationAwaiting,
    TradeDisbursementAwaiting,
}