export enum MappedType {
  PROFILE = 'PROFILE',
  INDIVIDUAL_ACCOUNT = 'INDIVIDUAL_ACCOUNT',
  CORPORATE_ACCOUNT = 'CORPORATE_ACCOUNT',
  TRUST_ACCOUNT = 'TRUST_ACCOUNT',
  BENEFICIARY_ACCOUNT = 'BENEFICIARY_ACCOUNT',
  COMPANY = 'COMPANY',
  STAKEHOLDER = 'STAKEHOLDER',
}

export enum MappedRecordStatus {
  DIRTY = 'DIRTY',
  CLEAN = 'CLEAN',
  TO_BE_DELETED = 'TO_BE_DELETED',
}
