name: functions-github-actions
on:
  push:
    branches:
      - development
      - integrations
      - staging
      - main
jobs:
  build-check-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          CURRENT_BRANCH=${GITHUB_REF##*/}
          echo "Current branch: ${CURRENT_BRANCH}"
          SHARED_ENVIRONMENT="TEST"
          if [ $CURRENT_BRANCH == "development" ]; then
            ENVIRONMENT="DEVELOPMENT"
          elif [ $CURRENT_BRANCH == "integrations" ]; then
            ENVIRONMENT="INTEGRATIONS"
          elif [ $CURRENT_BRANCH == "staging" ]; then
            ENVIRONMENT="STAGING"
          elif [ $CURRENT_BRANCH == "main" ]; then
            ENVIRONMENT="PRODUCTION"
            SHARED_ENVIRONMENT="PRODUCTION"
          else
            echo "Wrong branch";
            exit 1;
          fi
          echo "Current environment: ${ENVIRONMENT}"
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
          echo "SHARED_ENVIRONMENT=${SHARED_ENVIRONMENT}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: "Install dependencies"
        run: yarn install
      - name: "Install dependencies for pdf generator"
        run: cd devops/functions/pdfGenerator && yarn install
      - name: "Run unit tests"
        run: yarn tdd
      - name: "Deploy functions and migrate db"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POSTGRESQL_USER: ${{ secrets[format('{0}_POSTGRESQL_USER', env.ENVIRONMENT)] }}
          POSTGRESQL_PASSWORD: ${{ secrets[format('{0}_POSTGRESQL_PASSWORD', env.ENVIRONMENT)] }}
          WEB_APP_URL: ${{ secrets[format('{0}_WEB_APP_URL', env.ENVIRONMENT)] }}
          EMAIL_SEND_FROM: ${{ secrets.EMAIL_SEND_FROM }}
          EMAIL_REPLY_TO: ${{ secrets.EMAIL_REPLY_TO }}
          EMAIL_DOMAIN: ${{ secrets[format('{0}_EMAIL_DOMAIN', env.SHARED_ENVIRONMENT)] }}
          NORTH_CAPITAL_CLIENT_ID: ${{ secrets[format('{0}_NORTH_CAPITAL_CLIENT_ID', env.SHARED_ENVIRONMENT)] }}
          NORTH_CAPITAL_DEVELOPER_API_KEY: ${{ secrets[format('{0}_NORTH_CAPITAL_DEVELOPER_API_KEY', env.SHARED_ENVIRONMENT)] }}
          NORTH_CAPITAL_API_URL: ${{ secrets[format('{0}_NORTH_CAPITAL_API_URL', env.SHARED_ENVIRONMENT)] }}
          NORTH_CAPITAL_OFFERING_ID: ${{ secrets[format('{0}_NORTH_CAPITAL_OFFERING_ID', env.SHARED_ENVIRONMENT)] }}
          VERTALO_API_URL: ${{ secrets[format('{0}_VERTALO_API_URL', env.SHARED_ENVIRONMENT)] }}
          VERTALO_CLIENT_ID: ${{ secrets[format('{0}_VERTALO_CLIENT_ID', env.SHARED_ENVIRONMENT)] }}
          VERTALO_CLIENT_SECRET: ${{ secrets[format('{0}_VERTALO_CLIENT_SECRET', env.SHARED_ENVIRONMENT)] }}
          SNS_ORIGINATION_NUMBER: ${{ secrets.SNS_ORIGINATION_NUMBER }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          CHROMIUM_ENDPOINT: ${{ secrets.CHROMIUM_ENDPOINT }}
          DEALPATH_API_URL: ${{ secrets[format('{0}_DEALPATH_API_URL', env.SHARED_ENVIRONMENT)] }}
          DEALPATH_AUTHORIZATION_TOKEN: ${{ secrets[format('{0}_DEALPATH_AUTHORIZATION_TOKEN', env.SHARED_ENVIRONMENT)] }}
          DEALPATH_VERSION_HEADER: ${{ secrets[format('{0}_DEALPATH_VERSION_HEADER', env.SHARED_ENVIRONMENT)] }}
        run: |
          environment=${{env.ENVIRONMENT}}
          yarn "${environment,,}:deploy:functions"
          yarn "${environment,,}:invoke:migrateUp"
