name: functions-github-actions
on:
  push:
    tags:
      - GLOBAL_DEPLOYMENT
jobs:
  build-check-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: "Install dependencies"
        run: yarn install
      - name: "Deploy GLOBAL dependencies"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EMAIL_SEND_FROM: ${{ secrets.EMAIL_SEND_FROM }}
        run: |
          yarn "global:deploy"